language: python

cache:
  pip: true

sudo: false

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

os:
- linux

env:
  globals:
    - DISPLAY=:99.0

matrix:
  fast_finish: true
  allow_failures:
    - python: '3.6'

# repo branches to test
#branches:
#- master
# branches:
#   except:
#     - pytest

before_install:
# install and use Miniconda environment
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
# copy test netrc
- cp $TRAVIS_BUILD_DIR/python/sciserver/tests/data/testnetrc $HOME/.netrc

install:
- conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib ipython --quiet
- source activate test_env
- pip install -U pip wheel --quiet
- pip install --upgrade setuptools --quiet
- pip install -r requirements.txt --quiet
- pip install pytest --quiet
- pip install pytest-cov --quiet
- pip install pytest-sugar --quiet
- python setup.py install

before_script:
- export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/python

script:
- pytest python/sciserver/tests --cov python/sciserver --cov-report html -W ignore::DeprecationWarning

after_success:
- coveralls
